[package]
name = "fixture_macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "fixture_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2", features = ["extra-traits"] }
proc-macro2 = "1"
convert_case = "0.6.0"
